### ISSUE TITLE
Micro services structure

### ISSUE THREAD

**Issue by androsanta** [getapper/restlessness#94]
The new structure will have a folder *serverless-services* at the root of the project, with the corresponding serverless.json file for each service.

- serverless-services/
    - default.json
    - service1.json
    - ...

Points to address with the new structure:
1. **default service**: when creating a new project we could create a default service, to keep shared resources in a single place (for example the shared api-gateway)
2. **plugins**: a new plugin should be added to all services or we should specify a single service?
3. **api-gateway**: as (1) we should create a shared api-gateway at project creation
4. **cli**: the cli commands should handle more than one serverless.json
    example: for deploy it should call `serverless deploy --config serverless-services/default.json`
5. **services dependencies**: Should we allow services to depends on resource defined in other services? (Except for the default service). To keep things simple we may allow services to depends only from the default service. This make simpler also the deploy (first deploy the default service, then all the others, even concurrently)

### @restlessness/core
The association endpoint/service could be stored under the *config/endpoints.json* file. This way we do not have to specify each time to which service we are referring.

The **JsonServerless** class should handle more than one *serverless.json* file.

### @restlessness/dao-mongo
This package depends on **serverless-mongo-proxy**, which may be shared across all services.
If we share it then when invoking the lambda, and in particular when dao-mongo creates the lambda name (*serviceName-stage-functionName*) it could refer to the default service (currently the function crashes).

**Comment by antoniogiordano** [comment]
1. Agree with the default service, and we need a way to specify which one is it among all the services. What if the default service doesn't have any user lambdas, but only shared ones? So we have a single place for shared resources, and multiple services for APIs and CRONs. Every auth or proxy can be deployed there and be shared among all the others. The only issue right now can be warm-up, since it refers to the config file to get the list of lambdas, and should be installed in each one.
2. RLN plugins are installed at a project level, then we need to understand if current hooks are enough, or we need more to handle more services. We should test a dao, an auth, and general plugin to check if we are covering everything or not
3. I want to understand what should be the flow about this, so we can try to improve the developer experience. What are the steps necessary to have a working shared gateway between more services?
4. I think it's time to add a `restlessness deploy` command that will take care of this
5. If we go for the service deploying all the shared resources, we are good, and other services shouldn't share anything

## @restlessness/core
Correct

## @restlessness/dao-mongo
Agree

**Comment by androsanta** [comment]
Regarding the **JsonServerless** class, my idea is to refactor it as a **JsonServices** class, in which:
- the already defined methods remains, with modifications (like add/remove/update endpoint), plus others like addService etc..
- the structure of the files is:
    - file name: `${serviceName}.json`(example: *users.json*)
    - service name inside the file (it will be deployed with this name): `${projectName}-${serviceName}`
- a field *services* represents the defined services as an object with
    - key: name of the service (`${serviceName}` only)
    - value: content of the corresponding .json file

In this commits there is an initial implementation that allows to create an endpoint in a specified service

**Comment by antoniogiordano** [comment]
LGTM, can you create a PR in draft mode so I can check?

**Comment by antoniogiordano** [comment]
@androsanta we should add a offline.json to use for local testing and development purpose. So we don't have any issue with cross service reference, proxies, authorizers, and different serverless-offline servers to orchestrate

**Comment by androsanta** [comment]
Alright👍🏽 it should be generated on the fly when launching `restlessness dev` or should it be synchronized with the other service files?

**Comment by antoniogiordano** [comment]
I think it's better to have these files statically generated, so devs have always the chance to modify something if needed, both for dev then deploy ones. I'm committing some changes in this direction, let me know what you think about ;-)
